substitutions:
  project: Bedroom Sensor

esphome:
  name: bedroom_sensor
  platform: ESP8266
  board: esp01_1m

<<: !include common/wifi.yaml

captive_portal:

# Enable logging
logger:

<<: !include common/mqtt.yaml

ota:


sensor:
    
  - !include common/sensors/uptime.yaml
  - !include common/sensors/wifi_signal.yaml
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Bedroom Temperature"
      # filters:
      #   - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°C"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s
    model: DHT22

binary_sensor:
  - !include common/binary_sensors/status.yaml

switch:
  - platform: restart
    name: "Bedroom Sensor Restart"


