substitutions:
  project: Game Table Lamp
esphome:
  name: game_table_lamp
  platform: ESP8266
  board: esp01_1m

web_server:
  port: 80

wifi:
  !include common/wifi.yaml

captive_portal:

# Enable logging
logger:

<<: !include common/api.yaml
<<: !include common/ota.yaml
  
# switch:
#   - platform: gpio
#     pin: 4
#     id: relay
#     restore_mode: ALWAYS_OFF
#    # This is the actual rely control. Not setting the "name:" keeps it hidden

# output:
#   - platform: gpio
#     pin: 4
#     id: relay

#   - platform: template
#     id: switched_load
#     turn_on_action:
#       - switch.turn_on: relay
#       - switch.template.publish:
#           id: switched_load
#           state: ON
#     turn_off_action:
#       - switch.turn_off: relay
#       - switch.template.publish:
#           id: switched_load
#           state: OFF
#     lambda: |-
#       if (id(switched_load).state) {
#         return true;
#       } else {
#         return false;
#       }
    
    # This is the HASS switch to control the relay setup above
binary_sensor:
  - platform: gpio
    id: capacitive_switch
    pin: 14
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: the_light

light:
  - platform: monochromatic
    name: "$project LED"
    id: indicator
    output: front_led
    restore_mode: ALWAYS_OFF
    default_transition_length: 500ms
  - platform: binary
    name: $project
    id: the_light
    output: relay

output:
  - platform: esp8266_pwm
    id: front_led
    pin: 5
  - platform: gpio
    pin: 4
    id: relay
