substitutions:
  project: Garage Controller

esphome:
  name: garage_doors
  platform: ESP8266
  board: nodemcuv2

<<: !include common/wifi.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:


# status_led:
#   pin: 
#     number: GPIO2
#     inverted: True

sensor:
    
  - !include common/sensors/uptime.yaml
  - !include common/sensors/wifi_signal.yaml
  - platform: hx711
    name: "Water Softener Salt"
    dout_pin: D0
    clk_pin: D5
    gain: 128
    update_interval: 60s
    filters:
      - calibrate_linear:
        - 810208 -> 0
        - 894512 -> 10
    unit_of_measurement: lb


binary_sensor:
  - !include common/binary_sensors/status.yaml
  - platform: gpio
    pin: D1
    name: "Garage Motion"
    device_class: motion
  - platform: gpio
    pin: 
      number: GPIO10
      mode: INPUT_PULLUP
    device_class: garage_door
    filters: 
      - delayed_on_off: 500ms
    id: GarageSensor
switch:
  - platform: gpio
    pin: 
      number: D6
      mode: OUTPUT
      inverted: True
    id: garRelay
  - platform: gpio
    pin: 
      number: D7
      mode: OUTPUT
      inverted: True
    name: "Water Main"
#   - platform: template
#     icon: "mdi:garage"
#     turn_on_action:
#       - switch.turn_on: farRelay
#       - delay: 250ms
#       - switch.turn_off: farRelay
#     id: FarGarageSwitch

  - platform: restart
    name: "Garage Control Restart"

# cover:
#   - platform: template
#     name: "Garage"
#     lambda: |-
#       if (id(GarageSensor).state) {
#         return COVER_OPEN;
#       } else {
#         return COVER_CLOSED;
#       }
#     open_action:
#       - switch.turn_on: garRelay
#       - delay: 250ms
#       - switch.turn_off: garRelay
#     close_action:
#       - switch.turn_on: garRelay
#       - delay: 250ms
#       - switch.turn_off: garRelay
#     stop_action:
#       - switch.turn_on: garRelay
#       - delay: 90ms
#       - switch.turn_off: garRelay

