substitutions:
  project: Garage Controller

esphome:
  name: garage_doors
  platform: ESP8266
  board: nodemcuv2

<<: !include common/wifi.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:


# status_led:
#   pin: 
#     number: GPIO2
#     inverted: True

sensor:
    
  - !include common/sensors/uptime.yaml
  - !include common/sensors/wifi_signal.yaml
  - platform: dht
    pin: D2
    temperature:
      name: "Garage Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Garage Humidity"
    update_interval: 60s
    model: DHT22


binary_sensor:
  - !include common/binary_sensors/status.yaml
  - platform: gpio
    pin: D1
    name: "Garage Motion"
    device_class: motion
  - platform: gpio
    pin: 
      number: GPIO10
      mode: INPUT_PULLUP
    device_class: garage_door
    filters: 
      - delayed_on_off: 500ms
    id: NearGarageSensor
  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
    device_class: garage_door
    filters: 
      - delayed_on_off: 500ms  
    id: MiddleGarageSensor
  - platform: gpio
    pin:
      number: D0
      mode: INPUT_PULLUP
    device_class: garage_door
    filters: 
      - delayed_on_off: 500ms
    id: FarGarageSensor
switch:
  
  - platform: gpio
    pin: 
      number: D6
      mode: OUTPUT
      inverted: True
    id: midRelay
#   - platform: template
#     icon: "mdi:garage"
#     turn_on_action:
#       - switch.turn_on: midRelay
#       - delay: 250ms
#       - switch.turn_off: midRelay
#     id: MiddleGarageSwitch


  - platform: gpio
    pin: 
      number: D7
      mode: OUTPUT
      inverted: True
    id: farRelay
#   - platform: template
#     icon: "mdi:garage"
#     turn_on_action:
#       - switch.turn_on: farRelay
#       - delay: 250ms
#       - switch.turn_off: farRelay
#     id: FarGarageSwitch

  - platform: restart
    name: "Garage Control Restart"


cover:
  - platform: template
    name: "Far Garage"
    lambda: |-
      if (id(FarGarageSensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: farRelay
      - delay: 250ms
      - switch.turn_off: farRelay
    close_action:
      - switch.turn_on: farRelay
      - delay: 250ms
      - switch.turn_off: farRelay
    stop_action:
      - switch.turn_on: farRelay
      - delay: 90ms
      - switch.turn_off: farRelay
    
  - platform: template
    name: "Middle Garage"
    lambda: |-
      if (id(MiddleGarageSensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: midRelay
      - delay: 250ms
      - switch.turn_off: midRelay
    close_action:
      - switch.turn_on: midRelay
      - delay: 250ms
      - switch.turn_off: midRelay
    stop_action:
      - switch.turn_on: midRelay
      - delay: 90ms
      - switch.turn_off: midRelay

    optimistic: true
