substitutions:
  project: Under Cabinet Lights

esphome:
  name: under_cabinet_lights
  platform: ESP32
  board: nodemcu-32s

  platformio_options:
    lib_deps: NeoPixelBus@2.6.0

<<: !include common/wifi.yaml

# Enable logging
logger:

<<: !include common/mqtt.yaml

ota:

status_led:
  pin: GPIO2

light:
  - platform: neopixelbus
    type: GRBW
    pin: GPIO23
    num_leds: 180
    name: "Under Cabinet Lights"
    variant: SK6812
    id: ledStrip

sensor:
  - !include common/sensors/uptime.yaml
  - !include common/sensors/wifi_signal.yaml


switch:
  - platform: restart
    name: "Under Cabinet Lights Restart"


